import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";
import { CreateInvoiceDto } from "./dto/create-invoice.dto";
import {
  InvoiceStatus,
  PaymentMethod,
  PaymentProviderStatus,
  ReservationStatus,
} from "@prisma/client-hospitality";
import { EventPublisherService } from "../events/event-publisher.service";
import { EventTypes } from "../events/event-types";

export interface TaxBreakdownItem {
  name: string;
  rate: number;
  amount: number;
  taxableBase?: number;
}

export interface InvoiceCalculation {
  subtotal: number;
  taxBreakdown: TaxBreakdownItem[];
  totalAmount: number;
}

@Injectable()
export class InvoicesService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly eventPublisher: EventPublisherService,
  ) {}

  async findAll(
    organizationId: string,
    page: number,
    limit: number,
    status?: string,
  ) {
    const skip = (page - 1) * limit;
    const where: any = {
      property: { organizationId },
    };

    if (status) {
      where.status = status as InvoiceStatus;
    }

    const [data, total] = await Promise.all([
      this.prisma.invoice.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: "desc" },
        include: {
          guest: true,
          property: true,
          payments: true,
          reservation: {
            select: {
              id: true,
              reservationNumber: true,
              checkInDate: true,
              checkOutDate: true,
            },
          },
        },
      }),
      this.prisma.invoice.count({ where }),
    ]);

    return {
      data,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  async findOne(id: string, organizationId: string) {
    const invoice = await this.prisma.invoice.findFirst({
      where: { id, property: { organizationId } },
      include: {
        guest: true,
        property: true,
        payments: true,
        reservation: {
          include: {
            room: { include: { roomType: true } },
            guest: true,
          },
        },
      },
    });

    if (!invoice) {
      throw new NotFoundException("Invoice not found");
    }

    return invoice;
  }

  async preview(id: string, organizationId: string) {
    const invoice = await this.findOne(id, organizationId);

    return {
      invoiceNumber: invoice.invoiceNumber,
      issueDate: invoice.issueDate,
      dueDate: invoice.dueDate,
      property: {
        name: invoice.property.name,
        address: invoice.property.address,
        phone: invoice.property.phone,
        email: invoice.property.email,
        taxId: invoice.property.taxId,
        registrationNumber: invoice.property.registrationNumber,
        sltdaNumber: invoice.property.sltdaNumber,
      },
      guest: {
        name: `${invoice.guest.firstName} ${invoice.guest.lastName}`,
        email: invoice.guest.email,
        phone: invoice.guest.phone,
        localPhone: invoice.guest.localPhone,
        nicNumber: invoice.guest.nicNumber,
        passportNumber: invoice.guest.passportNumber,
        address: invoice.guest.address,
      },
      reservation: invoice.reservation,
      lineItems: [
        {
          description: `Room charges (${invoice.reservation.room.roomType.name} - Room ${invoice.reservation.room.roomNumber})`,
          amount: Number(invoice.subtotal),
        },
      ],
      subtotal: Number(invoice.subtotal),
      taxBreakdown: invoice.taxBreakdown,
      totalAmount: Number(invoice.totalAmount),
      paidAmount: Number(invoice.paidAmount),
      payments: invoice.payments.map((payment) => ({
        id: payment.id,
        amount: Number(payment.amount),
        method: payment.method,
        providerStatus: payment.providerStatus,
        providerRef: payment.providerRef,
        transactionDate: payment.transactionDate,
        notes: payment.notes,
      })),
      status: invoice.status,
      notes: invoice.notes,
    };
  }

  async create(
    organizationId: string,
    dto: CreateInvoiceDto,
    autoGenerated = false,
  ) {
    const reservation = await this.prisma.reservation.findFirst({
      where: {
        id: dto.reservationId,
        property: { organizationId },
      },
      include: {
        property: true,
        guest: true,
        room: { include: { roomType: true } },
      },
    });

    if (!reservation) {
      throw new NotFoundException("Reservation not found");
    }

    const existingInvoice = await this.prisma.invoice.findFirst({
      where: { reservationId: dto.reservationId },
    });

    if (existingInvoice && !autoGenerated) {
      throw new BadRequestException(
        "Invoice already exists for this reservation",
      );
    }

    // Calculate subtotal from room nights if not provided
    const nights = Math.max(
      1,
      Math.ceil(
        (reservation.checkOutDate.getTime() -
          reservation.checkInDate.getTime()) /
          (1000 * 60 * 60 * 24),
      ),
    );
    const reservationTotal = Number(reservation.totalAmount);
    const subtotal =
      dto.subtotal ??
      (reservationTotal > 0
        ? reservationTotal
        : Number(reservation.room.roomType.basePrice) * nights);

    const calculation = await this.calculateTaxes(organizationId, subtotal);
    const invoiceNumber = await this.generateInvoiceNumber();

    const invoice = await this.prisma.invoice.create({
      data: {
        invoiceNumber,
        reservation: { connect: { id: dto.reservationId } },
        property: { connect: { id: reservation.propertyId } },
        guest: { connect: { id: reservation.guestId } },
        dueDate: dto.dueDate ? new Date(dto.dueDate) : null,
        subtotal,
        taxBreakdown: calculation.taxBreakdown as any,
        totalAmount: calculation.totalAmount,
        paidAmount: 0,
        status: InvoiceStatus.draft,
        notes: dto.notes,
      },
      include: {
        guest: true,
        property: true,
        reservation: true,
      },
    });

    void this.eventPublisher.publish(EventTypes.INVOICE_GENERATED, {
      invoiceId: invoice.id,
      invoiceNumber: invoice.invoiceNumber,
      reservationId: invoice.reservationId,
      guestId: invoice.guestId,
      totalAmount: Number(invoice.totalAmount),
      organizationId,
    });

    return invoice;
  }

  async update(id: string, organizationId: string, dto: any) {
    const invoice = await this.findOne(id, organizationId);

    if (invoice.status === InvoiceStatus.paid) {
      throw new BadRequestException("Cannot update a paid invoice");
    }

    const subtotal = dto.subtotal ?? Number(invoice.subtotal);
    const calculation = await this.calculateTaxes(organizationId, subtotal);

    const { reservationId, propertyId, guestId, ...rest } = dto;
    return this.prisma.invoice.update({
      where: { id },
      data: {
        ...rest,
        subtotal,
        taxBreakdown: calculation.taxBreakdown as any,
        totalAmount: calculation.totalAmount,
        ...(reservationId && {
          reservation: { connect: { id: reservationId } },
        }),
        ...(propertyId && { property: { connect: { id: propertyId } } }),
        ...(guestId && { guest: { connect: { id: guestId } } }),
      },
      include: {
        guest: true,
        property: true,
        reservation: true,
      },
    });
  }

  async remove(id: string, organizationId: string) {
    await this.findOne(id, organizationId);

    return this.prisma.invoice.delete({
      where: { id },
    });
  }

  async markPaid(id: string, organizationId: string) {
    const invoice = await this.findOne(id, organizationId);
    const balance = Number(invoice.totalAmount) - Number(invoice.paidAmount);

    const updated = await this.prisma.$transaction(async (tx) => {
      if (balance > 0) {
        await tx.payment.create({
          data: {
            invoice: { connect: { id: invoice.id } },
            reservation: { connect: { id: invoice.reservationId } },
            organizationId,
            amount: balance,
            method: PaymentMethod.cash,
            providerStatus: PaymentProviderStatus.succeeded,
            notes: "Marked paid from invoice action",
          },
        });
      }

      await tx.reservation.update({
        where: { id: invoice.reservationId },
        data: {
          paidAmount: invoice.totalAmount,
          paymentStatus: "paid",
        },
      });

      return tx.invoice.update({
        where: { id },
        data: {
          paidAmount: invoice.totalAmount,
          status: InvoiceStatus.paid,
        },
        include: {
          guest: true,
          property: true,
          reservation: true,
          payments: true,
        },
      });
    });

    return updated;
  }

  async generateFromCheckout(reservationId: string, organizationId: string) {
    return this.create(organizationId, { reservationId }, true);
  }

  async calculateTaxes(
    organizationId: string,
    subtotal: number,
  ): Promise<InvoiceCalculation> {
    const activeRates = await this.prisma.taxRate.findMany({
      where: { organizationId, isActive: true },
    });

    const getRate = (name: string) =>
      activeRates.find((r) => r.name.toLowerCase() === name.toLowerCase());

    const calculateAmount = (
      rate: ReturnType<typeof getRate>,
      taxableBase: number,
    ) => {
      if (!rate) return 0;
      if (rate.type === "fixed") return Number(rate.rate);
      return taxableBase * (Number(rate.rate) / 100);
    };

    const serviceChargeRate = getRate("Service Charge");
    const tdlRate = getRate("TDL");
    const ssclRate = getRate("SSCL");
    const vatRate = getRate("VAT");

    const serviceCharge = calculateAmount(serviceChargeRate, subtotal);
    const tdlBase = subtotal + serviceCharge;
    const tdl = calculateAmount(tdlRate, tdlBase);
    const sscl = calculateAmount(ssclRate, tdlBase);
    const vatBase = subtotal + serviceCharge + tdl + sscl;
    const vat = calculateAmount(vatRate, vatBase);

    const taxBreakdown: TaxBreakdownItem[] = [];

    if (serviceChargeRate && Number(serviceChargeRate.rate) > 0) {
      taxBreakdown.push({
        name: "Service Charge",
        rate: Number(serviceChargeRate.rate),
        taxableBase: Number(subtotal.toFixed(2)),
        amount: Number(serviceCharge.toFixed(2)),
      });
    }
    if (tdlRate && Number(tdlRate.rate) > 0) {
      taxBreakdown.push({
        name: "TDL",
        rate: Number(tdlRate.rate),
        taxableBase: Number(tdlBase.toFixed(2)),
        amount: Number(tdl.toFixed(2)),
      });
    }
    if (ssclRate && Number(ssclRate.rate) > 0) {
      taxBreakdown.push({
        name: "SSCL",
        rate: Number(ssclRate.rate),
        taxableBase: Number(tdlBase.toFixed(2)),
        amount: Number(sscl.toFixed(2)),
      });
    }
    if (vatRate && Number(vatRate.rate) > 0) {
      taxBreakdown.push({
        name: "VAT",
        rate: Number(vatRate.rate),
        taxableBase: Number(vatBase.toFixed(2)),
        amount: Number(vat.toFixed(2)),
      });
    }

    const totalAmount = Number(
      (subtotal + serviceCharge + tdl + sscl + vat).toFixed(2),
    );

    return {
      subtotal: Number(subtotal.toFixed(2)),
      taxBreakdown,
      totalAmount,
    };
  }

  private async generateInvoiceNumber(): Promise<string> {
    const today = new Date();
    const datePart = today.toISOString().slice(0, 10).replace(/-/g, "");
    const count = await this.prisma.invoice.count({
      where: {
        invoiceNumber: { startsWith: `INV-${datePart}` },
      },
    });
    const sequence = (count + 1).toString().padStart(4, "0");
    return `INV-${datePart}-${sequence}`;
  }
}
