// Import all widgets to trigger their registerWidget() side effects.
// Add new widget imports here as the catalog grows.
import './TodaysAttendanceWidget'
import './PendingLeaveWidget'
import './PendingOvertimeWidget'
import './PendingExpensesWidget'
import './HeadcountWidget'
import './RecentClockInsWidget'
import './WeeklyTrendWidget'
import './AnnouncementsWidget'
import './SpoofingReviewWidget'
import './PendingCompOffWidget'
import './PendingEncashmentWidget'
import './PendingCorrectionsWidget'
import './PendingDocSignaturesWidget'
import './PayrollSummaryWidget'
import './PendingShiftSwapsWidget'
import './RosterAdherenceWidget'
import './TrainingOverviewWidget'
import './PerformanceReviewsWidget'
import './AssetsOverviewWidget'
import './UpcomingEventsWidget'
import './RecentActivityWidget'
