-- AlterTable
ALTER TABLE "clients" ADD COLUMN     "industry" TEXT,
ADD COLUMN     "website" TEXT,
ADD COLUMN     "timezone" TEXT DEFAULT 'UTC',
ADD COLUMN     "language" TEXT DEFAULT 'en',
ADD COLUMN     "businessDescription" TEXT,
ADD COLUMN     "adminEmail" TEXT,
ADD COLUMN     "adminPhone" TEXT,
ADD COLUMN     "chatwootAdminUserId" INTEGER,
ADD COLUMN     "aiModel" TEXT DEFAULT 'kimi-latest',
ADD COLUMN     "maxTokens" INTEGER DEFAULT 1024,
ADD COLUMN     "confidenceThreshold" DOUBLE PRECISION DEFAULT 0.7,
ADD COLUMN     "aiEnabled" BOOLEAN DEFAULT true,
ADD COLUMN     "welcomeMessage" TEXT DEFAULT 'Hello! How can we help you today?',
ADD COLUMN     "fallbackMessage" TEXT DEFAULT 'I''m sorry, I didn''t understand that. Let me connect you with our team.',
ADD COLUMN     "handoffKeywords" TEXT DEFAULT 'human,agent,person,manager,supervisor',
ADD COLUMN     "operatingHoursStart" TEXT DEFAULT '09:00',
ADD COLUMN     "operatingHoursEnd" TEXT DEFAULT '17:00',
ADD COLUMN     "closedDays" TEXT DEFAULT 'Saturday,Sunday',
ADD COLUMN     "verifyToken" TEXT DEFAULT gen_random_uuid()::text,
ADD COLUMN     "webhookUrl" TEXT,
ADD COLUMN     "metaWebhookStatus" TEXT DEFAULT 'pending',
ADD COLUMN     "lastWebhookAt" TIMESTAMP(3);
