import type { OrgChartData } from './types'

/**
 * Mock org chart matching Codex RPC shape.
 * 4-level tree for scaffold testing.
 */
export const mockOrgChartData: OrgChartData = [
  // Level 0 — CEO
  {
    employee_id: 'e001',
    manager_id: null,
    first_name: 'Aravinda',
    last_name: 'Perera',
    full_name: 'Aravinda Perera',
    photo_url: null,
    job_title: 'Chief Executive Officer',
    date_of_birth: '1978-06-12',
    hire_date: '2016-01-10',
    department_id: 'd001',
    department_name: 'Executive',
    department_code: 'EXEC',
    parent_department_id: null,
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 0,
    path_ids: ['e001'],
    path_names: ['Aravinda Perera'],
    sort_path: '00001',
    direct_reports_count: 3,
    has_children: true,
    is_current_user: false,
  },
  // Level 1 — Direct reports to CEO
  {
    employee_id: 'e002',
    manager_id: 'e001',
    first_name: 'Dilani',
    last_name: 'Fernando',
    full_name: 'Dilani Fernando',
    photo_url: null,
    job_title: 'Chief Technology Officer',
    date_of_birth: '1984-09-18',
    hire_date: '2018-03-05',
    department_id: 'd002',
    department_name: 'Engineering',
    department_code: 'ENG',
    parent_department_id: 'd001',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 1,
    path_ids: ['e001', 'e002'],
    path_names: ['Aravinda Perera', 'Dilani Fernando'],
    sort_path: '00001.00001',
    direct_reports_count: 2,
    has_children: true,
    is_current_user: false,
  },
  {
    employee_id: 'e003',
    manager_id: 'e001',
    first_name: 'Sanjeev',
    last_name: 'Ranasinghe',
    full_name: 'Sanjeev Ranasinghe',
    photo_url: null,
    job_title: 'Chief Financial Officer',
    date_of_birth: '1980-02-22',
    hire_date: '2017-07-15',
    department_id: 'd003',
    department_name: 'Finance',
    department_code: 'FIN',
    parent_department_id: 'd001',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 1,
    path_ids: ['e001', 'e003'],
    path_names: ['Aravinda Perera', 'Sanjeev Ranasinghe'],
    sort_path: '00001.00002',
    direct_reports_count: 1,
    has_children: true,
    is_current_user: false,
  },
  {
    employee_id: 'e004',
    manager_id: 'e001',
    first_name: 'Nadeeka',
    last_name: 'Wijesekara',
    full_name: 'Nadeeka Wijesekara',
    photo_url: null,
    job_title: 'Head of People',
    date_of_birth: '1986-11-08',
    hire_date: '2019-02-01',
    department_id: 'd004',
    department_name: 'Human Resources',
    department_code: 'HR',
    parent_department_id: 'd001',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 1,
    path_ids: ['e001', 'e004'],
    path_names: ['Aravinda Perera', 'Nadeeka Wijesekara'],
    sort_path: '00001.00003',
    direct_reports_count: 1,
    has_children: true,
    is_current_user: false,
  },
  // Level 2 — Engineering
  {
    employee_id: 'e005',
    manager_id: 'e002',
    first_name: 'Kasun',
    last_name: 'Jayawardena',
    full_name: 'Kasun Jayawardena',
    photo_url: null,
    job_title: 'Engineering Manager',
    date_of_birth: '1990-04-03',
    hire_date: '2021-06-01',
    department_id: 'd002',
    department_name: 'Engineering',
    department_code: 'ENG',
    parent_department_id: 'd001',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 2,
    path_ids: ['e001', 'e002', 'e005'],
    path_names: ['Aravinda Perera', 'Dilani Fernando', 'Kasun Jayawardena'],
    sort_path: '00001.00001.00001',
    direct_reports_count: 2,
    has_children: true,
    is_current_user: true,
  },
  {
    employee_id: 'e006',
    manager_id: 'e002',
    first_name: 'Tharindi',
    last_name: 'Silva',
    full_name: 'Tharindi Silva',
    photo_url: null,
    job_title: 'Product Manager',
    date_of_birth: '1992-07-19',
    hire_date: '2022-01-17',
    department_id: 'd005',
    department_name: 'Product',
    department_code: 'PROD',
    parent_department_id: 'd002',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 2,
    path_ids: ['e001', 'e002', 'e006'],
    path_names: ['Aravinda Perera', 'Dilani Fernando', 'Tharindi Silva'],
    sort_path: '00001.00001.00002',
    direct_reports_count: 0,
    has_children: false,
    is_current_user: false,
  },
  // Level 2 — Finance
  {
    employee_id: 'e007',
    manager_id: 'e003',
    first_name: 'Roshan',
    last_name: 'Kumar',
    full_name: 'Roshan Kumar',
    photo_url: null,
    job_title: 'Senior Accountant',
    date_of_birth: '1988-12-04',
    hire_date: '2020-08-10',
    department_id: 'd003',
    department_name: 'Finance',
    department_code: 'FIN',
    parent_department_id: 'd001',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 2,
    path_ids: ['e001', 'e003', 'e007'],
    path_names: ['Aravinda Perera', 'Sanjeev Ranasinghe', 'Roshan Kumar'],
    sort_path: '00001.00002.00001',
    direct_reports_count: 0,
    has_children: false,
    is_current_user: false,
  },
  // Level 2 — HR
  {
    employee_id: 'e008',
    manager_id: 'e004',
    first_name: 'Priyani',
    last_name: 'Gamage',
    full_name: 'Priyani Gamage',
    photo_url: null,
    job_title: 'HR Operations Lead',
    date_of_birth: '1991-03-14',
    hire_date: '2021-10-20',
    department_id: 'd004',
    department_name: 'Human Resources',
    department_code: 'HR',
    parent_department_id: 'd001',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 2,
    path_ids: ['e001', 'e004', 'e008'],
    path_names: ['Aravinda Perera', 'Nadeeka Wijesekara', 'Priyani Gamage'],
    sort_path: '00001.00003.00001',
    direct_reports_count: 0,
    has_children: false,
    is_current_user: false,
  },
  // Level 3 — Engineering team
  {
    employee_id: 'e009',
    manager_id: 'e005',
    first_name: 'Lahiru',
    last_name: 'Bandara',
    full_name: 'Lahiru Bandara',
    photo_url: null,
    job_title: 'Frontend Engineer',
    date_of_birth: '1996-06-06',
    hire_date: '2026-05-20',
    department_id: 'd002',
    department_name: 'Engineering',
    department_code: 'ENG',
    parent_department_id: 'd001',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 3,
    path_ids: ['e001', 'e002', 'e005', 'e009'],
    path_names: ['Aravinda Perera', 'Dilani Fernando', 'Kasun Jayawardena', 'Lahiru Bandara'],
    sort_path: '00001.00001.00001.00001',
    direct_reports_count: 0,
    has_children: false,
    is_current_user: false,
  },
  {
    employee_id: 'e010',
    manager_id: 'e005',
    first_name: 'Imashi',
    last_name: 'Dissanayake',
    full_name: 'Imashi Dissanayake',
    photo_url: null,
    job_title: 'Backend Engineer',
    date_of_birth: '1995-01-29',
    hire_date: '2024-04-22',
    department_id: 'd002',
    department_name: 'Engineering',
    department_code: 'ENG',
    parent_department_id: 'd001',
    branch_id: 'b001',
    branch_name: 'Head Office',
    depth: 3,
    path_ids: ['e001', 'e002', 'e005', 'e010'],
    path_names: ['Aravinda Perera', 'Dilani Fernando', 'Kasun Jayawardena', 'Imashi Dissanayake'],
    sort_path: '00001.00001.00001.00002',
    direct_reports_count: 0,
    has_children: false,
    is_current_user: false,
  },
]
